// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlkyxnoebkwrgdsjxulr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sa3l4bm9lYmt3cmdkc2p4dWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzM1NTAsImV4cCI6MjA2MDQwOTU1MH0.VliiRnrnnc4jiJphHEno-tHdg83USCCP7JcwOCXiwyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);